spring:
  application:
    name: backend

  datasource:
    url: jdbc:mysql://localhost:3306/umc?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: "dkttkfkqldk!2"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create        # ⬅ create → update 로 권장
    properties:
      hibernate:
        format_sql: true
    show-sql: true             # ⬅ 위치 수정 권장

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

jwt:
  secret: "ASDFQWERZXCV123412341234ABCDABCD"
  access-expire: 14400000
