spring:
  application:
    name: backend

  sql:
    init:
      mode: always

  datasource:
    url: jdbc:mysql://localhost:3306/mobile?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: "dkttkfkqldk!2"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update        # ⬅ create → update 로 권장
    properties:
      hibernate:
        format_sql: true
    show-sql: false             # ⬅ 위치 수정 권장

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

app:
  base-url: http://172.16.83.59:8080

jwt:
  secret: "ASDFQWERZXCV123412341234ABCDABCD"
  access-expire: 14400000
server:
  address: 0.0.0.0
